name: dev

on:
  push:
    # file paths to consider in the event. Optional; defaults to all.
    paths:
      - "doc/**"
      - ".github/workflows/**"
      - "!**.md"
  pull_request:
    # file paths to consider in the event. Optional; defaults to all.
    paths:
      - "doc/**"
      - ".github/workflows/**"
      - "!**.md"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Change path
        run: cd /

      - name: Install md2md
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install md2md -g # will run `yarn install` command

