name: dev

on: push

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build "
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Delete And Push
        run: |
          sudo apt-get update
          sudo apt-get install jq
          cd ../
          git clone https://.:${{ secrets.P_GITHUB_TOKEN }}@github.com/nameczz/a-project.git target
          git config --global user.email "Milvus-doc-bot@zilliz.com"
          git config --global user.name "Milvus-doc-bot"
          cd target
          rm -rf `cat version.json | jq -r .version`
          mkdir `cat version.json | jq -r .version`
          cd ../
          cp -avr ./milvus-docs/** ./target/`cat version.json | jq -r .version`
          cd target
          git add .
          git commit -m "Release new docs "
          git push -f origin master
